# Generated by Django 5.2.16 on 2026-09-20 10:04

import arch_media.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteChrome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(default='arch', max_length=50, unique=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site chrome',
                'verbose_name_plural': 'Site chrome',
            },
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file', models.FileField(max_length=500, upload_to=arch_media.models.arch_upload_to)),
                ('storage_key', models.CharField(blank=True, max_length=500)),
                ('url', models.CharField(blank=True, max_length=1000)),
                ('sort_order', models.IntegerField(default=0)),
                ('slot', models.CharField(blank=True, max_length=100)),
                ('site', models.CharField(default='arch', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['site', 'sort_order'], name='arch_media__site_38c89e_idx'), models.Index(fields=['site', 'slot'], name='arch_media__site_d5f7dd_idx')],
            },
        ),
    ]
